<section class="slider-home4">
    <div class="slider-inside container">
        <div class="slide-text">
            <h1>Terms &amp; Conditions</h1>
        </div>
    </div>
</section>
<!--slider complete-->


<!--policy-start-->

<section class="privacy-section">
    <div class="container">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#professionals" aria-controls="professionals" role="tab" data-toggle="tab">Professionals</a></li>
            <li role="presentation"><a href="#clients" aria-controls="clients" role="tab" data-toggle="tab">Clients</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="professionals">
                <h2 class="heading02">Terms of Service for Professionals</h2>
                <p>
                    These Terms of Service regulate the use of the mobile and online services, business tools provided by Hair Decoded, Inc.</p>
                <p>
                    KINDLY STUDY THESE TERMS OF SERVICE CAREFULLY. THIS IS A LEGAL AGREEMENT BETWEEN HAIR DECODED AND YOU WHICH REGULATES YOUR ACCESS AND USE OF THE SERVICES. BY ACCEPTING THESE TERMS OF SERVICE, EITHER BY EXECUTING A SUBSCRIPTION AGREEMENT OR  BY YOUR USE OF THE SERVICE, YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU HAVE READ, FULLY UNDERSTAND, AND ARE BOUND TO ALL OF THE TERMS AND CONDITIONS AND YOUR REPRESENTATION THAT YOU ARE 18 YEARS OF AGE OR OLDER. IF YOU ARE ENTERING INTO THESE TERMS OF SERVICE ON BEHALF OF A COMPANY OR OTHER ENTITY, YOU ACKNOWLEDGE THAT YOU HAVE THE AUTHORITY TO BIND THE COMPANY OR ENTITY TO THESE TERMS OF SERVICE.</p>

                <p>The Services are protected by copyright laws and international copyright treaties. Unauthorized reproduction or distribution of the Services, or any part of them, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. The Services are licensed, not sold.
                </p>

                <h2 class="heading01">The Hair Decoded Services</h2>
                <p>
                    The Hair Decoded platform connects salons, stylists and Professionals providing hair, beauty and other health and wellness services with clients seeking these services. The Professionals and Clients are all users of the Services provided by Hair Decoded and are hereinafter referred to collectively as "Users."
                </p>

                <h2 class="heading01">Fees and Payment</h2>

                <h2 class="heading01 pad-top-none">Fees</h2>

                <p>
                    Payments for the Subscription are set forth herein, online and in a separately executed or accepted Subscription agreement between you and Hair Decoded.
                </p>
                <p>
                    You agree to pay all Hair Decoded Subscription Fees, including but not limited to other applicable fees as may be agreed to by you. You agree that your fees may not be refunded or transferred except for as expressly provided in these Terms of Service. Unless otherwise specified in a Subscription, such fees will be billed in advance for each billing period and are non-refundable.
                </p>
                <p>
                    Each Professional will authorize us to confirm that the credit card account or any other payment method associated with their Account and used in connection with the Services is and remains in good standing with a financial institution as long as the Professional is using the Services. Each Professional also grants us approval to collect credit reports or other background inquiries regularly to assess the Professional's eligibility to continue the use of the Services. All amounts are payable in U.S. dollars, and users of the Service expressly authorize us to charge where applicable: (i) Subscription Fees, to be billed during a Subscription Period (ii) other fees for Services purchased, including, but not limited to, Add-Ons (iii) charges for use of the Services in excess of visitor, page, or other limitations, and (iv) taxes connected with your use of these Services.
                </p>
                <h2 class="heading01"> Bill Cycle</h2>
                <p>
                    Your Subscription starts on the date you signed up for a Subscription and complete payment. Unless otherwise stated at the time of signing up, each Subscription cycle is valid for one-month ("Subscription Period"), and will automatically renew on a monthly basis until we terminate the Subscription, or you request for subscription cancellation or account deletion via the Services or by email to <a href="mailto:cancelsubscription@hairdecoded.com">cancelsubscription@hairdecoded.com</a>.
                </p>
                <p>Unless otherwise stated, you will be billed on the monthly anniversary of the first completed payment to us for your Subscription (For example, if your Subscription begins on August 1st, it will renew automatically on September 1st, October 1st, and so on. If your Subscription starts on a date that doesn't occur every billing cycle (e.g., the 31st), you will be billed on the last day of every month. We reserve the right to change the timing of our billing. You acknowledge that the amount billed to you each month may vary due to promotions and adding or upgrading/downgrading your Subscription plan, and you authorize Hair Decoded to charge you for these differing amounts as necessary.</p>

                <h2 class="heading01">Subscription</h2>
                <p>
                    We reserve the right to modify our billing rates for the Subscription Services at any time upon (14) days prior notice. Should you continue to use the Services after these changes go into effect, you will be responsible for paying the new Subscription/billing rate. You must agree to the change in pricing to continue to use the Services. To withdraw your consent, you will need to cancel your account by logging into your account and following the cancellation process, or requesting via <a href="mailto:cancelsubscription@hairdecoded.com">cancelsubscription@hairdecoded.com</a>.
                </p>
                <h2 class="heading01">Trials</h2> 
                <p>
                    Hair Decoded may, from time to time and at our sole discretion, offer the opportunity of trial memberships which include free or discounted access to the Subscription for a limited time.  Before the end of the Trial Period, you must decide whether you would like to continue using the service. Each trial membership will automatically convert to a regular monthly subscription unless cancelled no more than forty-eight (48) hours prior to the end of your trial period. To cancel your subscription, log into your account and follow the cancellation process, or email <a href="mailto:cancelsubscription@hairdecoded.com">cancelsubscription@hairdecoded.com</a>.
                </p>
                <h2 class="heading01">Termination of Subscription</h2>
                <p>You may cancel your monthly Subscription at any time either from within your Account or by sending an email to cancelsubscription@hairdecoded.com. Cancellations must be completed at least 48 hours prior to the end of your then-current monthly Subscription Period; otherwise, billing for the next month or year will be processed automatically. Cancellations performed after billing are not entitled to refunds, in whole or in part. If you have any questions about your individual billing cycle, please log into your account to view your billing cycle details, or contact us at <a href="mailto:support@hairdecoded.com">support@hairdecoded.com</a>.</p>
                <p>Following cancellation, you will continue to have access to the Subscription Services through the end of your current billing cycle.</p>
                <h2 class="heading01">The Hair Decoded Platform</h2>
                <p>Hair Decoded only provides an environment for Professionals and Clients to connect and serves only as a platform to assist the provision of Styling Services. HAIR DECODED IS NOT RESPONSIBLE FOR THE CONDUCT OF ANY USER OF THE SERVICES AND YOU HEREBY RELEIVE THE COMPANY AND ITS AFFILIATES OR LICENSORS FROM ANY LIABILITY RELATED THERETO.</p>
                <p>Hair Decoded does not have control over the quality, suitability, legality, failure to provide, or any other aspect whatsoever of any Styling Services provided by Professionals nor the integrity of the actions or omissions whatsoever of any Professionals or Clients. Hair Decoded does not verify that any User is who they claim to be or is accurately representing themselves and does not verify or confirm any representations with respect to Styling Services on the Services.</p>
                <p>Hair Decoded takes what it believes to be reasonable efforts to ensure secure transmission of your information to third parties who assess and process payments, however, Hair Decoded is not responsible for any fees or charges set by third parties or any errors in the processing of payments by third parties, including any errors that result from third-party negligence, improper transmission of payment information, a Client's mistaken submission of payment information or submission of erroneous payment information.</p>
                <p>You agree that you will keep to the reservations made by Clients through the Services, or communicate with them in advance to resolve any scheduling conflicts to the Client's and Hair Decoded's satisfaction.</p>

                <h2 class="heading01">Accounts</h2>
                <h2 class="heading01 pad-top-none">Account Registration</h2>

                <p>You further consent and authorize us to verify your Registration Data as required for your use of and access to the Services. We reserve the right to suspend or terminate the Account of any User who provides inaccurate information. </p>
                <p>A right is granted to use the Services provided by Hair Decoded when you create a Hair Decoded account and pay the applicable subscription fee, subject to the restrictions in these Terms of Service and any other restrictions stated to you by us in writing. The registration process will include a request for information, including your name and other personal information (including information regarding any licensing and registration applicable to you where you provide the Services). To gain access to any funds that you accept through the services, you will have to complete this.</p>
                <p>You agree to provide true, accurate, current, and complete information about yourself, or the entity you represent, and you agree not to misrepresent your Profile Information. You further agree that, in providing such Registration Data, you will not knowingly omit or misrepresent any material facts or information and that you will promptly enter corrected or updated Registration Data via the Services or otherwise advise us promptly in writing of any changes or updates to your Registration Data. You also agree and authorize us to check and verify the registration data you provided as required for your use and access to the Services. Hair Decoded reserves the right to terminate the account of any user who provides untrue, or incomplete information, or who fails to comply with the account registration requirements.</p>
                <h2 class="heading01">Account Identification</h2>
                <p>You will receive a unique user identification and password in connection with your Account, once you register for the services. You agree to use you or your business' real and accurate name when signing up for an account. It is required that you choose an appropriate and non-offensive Account ID. Ideally, the ID you select should be a reasonably descriptive name that clearly identifies you or your business. This is the name that will appear on your credit or debit card statement for all payments you accept using the Services. Hair Decoded reserves the right to remove or reclaim any Account ID if we believe, in our sole discretion, the Account ID is inappropriate, offensive or potentially violates the rights of a third party.</p>
                <h2 class="heading01">User Account</h2>
                <p>You agree that your Account will be for your own use alone, and you agree not to disclose your User ID to any Third Party in order for them to use the Services under any circumstances. You are solely responsible for all activities that occur within your Account, maintaining the confidentiality of your Account IDs and for any charges, damages, liabilities or losses incurred or suffered as a result of your failure to do so. Hair Decoded is not liable for any harm caused by or related to the theft of your Account IDs, your disclosure of your Account IDs, or your decision to allow another person to access or use the Services using your Account IDs. Furthermore, you are solely and entirely responsible for any and all activities that occur under your Account including any charges incurred relating to the Services. If you become aware of any unauthorized use of your Account or Profile Information, you are responsible for notifying Hair Decoded immediately. It is your responsibility to update or change any Account or Profile Information, as needed or desired. You agree that the complete privacy of your data and messages transmitted while using the Services cannot be guaranteed.</p>
                <h2 class="heading01">Linking Accounts</h2>
                <p>You may link your Account with other online accounts you may have with third party service providers by either providing your Third Party Account login information through the Services; or authorizing Hair Decoded to access your Third Party Account, as is allowed under the applicable terms and conditions that govern your use of each Third Party Account. You agree that you have the authority to disclose your Third Party Account login information to Hair Decoded or permit Hair Decoded access to your Third Party Account, without you going against any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating Hair Decoded to make any payments or making Hair Decoded subject to any usage limitations imposed by such third party service providers. </p>
                <p>By permitting Hair Decoded access to any Third Party Accounts, you understand that Hair Decoded may access and store any content that you have provided to and stored in your Third Party Account so that it is available on and via the Services through your Account, including without exception to any friend lists, and Hair Decoded may transmit and receive additional information to your Third Party Account to the extent you are notified when you link your Account with the Third Party Account. Unless stated otherwise in these Terms of Service, all SNS Content, shall be regarded as Content (as defined below) for all purposes of these Terms of Service. Depending on which Third Party Accounts you choose and subject to the privacy settings that you have selected in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts may be available on and through your Account on the Services. Kindly note that if a Third Party Account or associated service is unavailable or Hair Decoded's access to such Third Party Account is cancelled by the third party service provider, then SNS Content may no longer be available on and through the Services. You have the choice of terminating the connection between your Account and your Third Party Accounts at any time. PLEASE BE INFORMED THAT YOUR RELATIONSHIP WITH THE THIRD PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD PARTY ACCOUNTS IS REGULATED SOLELY BY YOUR CONTRACT(S) WITH SUCH THIRD PARTY SERVICE PROVIDERS. Hair Decoded does not attempt to review any SNS Content for any reason, including but not limited to, accuracy, legality or non-infringement, and Hair Decoded does not take responsibility for any SNS Content.</p>
                <p>You agree that the Services may access your e-mail address book associated with a Third Party Account and your contacts list stored on your mobile device solely for the purposes of identifying and informing you of those contacts who have also registered to use the Services. At your request made via e-mail to <a href="mailto:hairdecoded@HairDecoded.com">hairdecoded@HairDecoded.com</a>, Hair Decoded will terminate the connection between Hair Decoded Services and your Third Party Account and any information stored on Hair Decoded's servers that was secured through such Third Party Account will be hidden, except the username and profile picture associated with your Account.</p>
                <p>The Services may contain links to third party websites that are not owned or governed by Hair Decoded. Hair Decoded does not control, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. Furthermore, Hair Decoded will not and cannot censor or modify the content of any third-party site. By using the Services, you expressly exempt Hair Decoded from any and all liability arising from your use of any third-party website.</p>

                <h2 class="heading01">Termination of Subscription and Accounts</h2>
                <h2 class="heading01 pad-top-none">Right to Terminate</h2>

                <p>Hair Decoded reserves the right to terminate this Agreement at any time, for any reason or no reason at any time, and at our sole discretion, without liability. A reason for such termination may be, but is not limited to, failure to comply with these terms. Hair Decoded reserves the right to modify, suspend your Account (including the funds in your Account) if you fail to comply with these Terms of Service, any other agreement you have with Hair Decoded, including, without limitation to the EULA, or Hair Decoded's policies, pose an unacceptable credit or fraud risk to us, provide any false, incomplete, or misleading information or otherwise engage in fraudulent or illegal conduct or for any other reason in Hair Decoded's sole discretion. This includes the right to modify or terminate any Subscription prior to the end of any pre-paid period.</p>
                <p>You may opt out of these Terms of Service and/or the EULA by terminating your Account at any time. Upon closure of an Account, any pending transactions will be terminated. Any funds that we are holding for you at the time of closure, less any applicable Fees, will be paid out to you according to your payout schedule, (assuming all payout-related authentication requirements have been fulfilled). If an investigation is pending at the time of Account closure, we may keep your funds as described herein. If you are later determined to be entitled to some or all of the funds in dispute, we will release those funds to you.</p>
                <h2 class="heading01">Effects of Termination</h2>
                <p>If for any reason, or no reason your Subscription and/or Account is terminated or suspended, you agree to continue to be bound by these Terms of Service, to discontinue using the Services immediately, that any licenses grant to you under these Terms of Service shall end, that we reserve the right (but have no obligation) to hide or delete all of your information and account data stored on our servers, and that Hair Decoded shall not be liable to you or any third party for termination or suspension of access to the Services or for deletion or hiding of your information or account data. You also agree that Hair Decoded may keep and use your information and account data as needed to comply with investigations and applicable law.</p>
                <p>We will not be responsible for compensation, reimbursement, or damages as a result of your use of the Services, or in connection with any termination or suspension of the Services. Any termination of these Terms of Service does not exempt you of any obligations to pay any Fees or costs accrued before the termination and any other amounts owed by you to us as stated in these Terms of Service.</p>
                <h2 class="heading01">Professional Accounts</h2>
                <p>The Service may be used by Professionals to offer Styling Services only through their business or personal website or software, and we reserve authority as to the implementation and use of the Services on the Professional's Site. </p>
                <p>By creating an Account as a Professional, you certify that you are, or if you are a salon, merchant or other business entity, all of your employees, independent contractors or agents who are providing the Styling Services each are, a licensed professional and that your business information is correctly represented on Hair Decoded.</p>
                <p>By creating an Account as a Professional, you agree  that you will not accept fees from or in connection with the following businesses or business activities: any fraudulent activity or goods, buyers or membership clubs, credit repair agencies, credit protection or identity theft protection services, direct marketing services, infomercial sales, internet/mail order/telephone order pharmacies or pharmacy referral services, unauthorized multi-level marketing businesses, inbound or outbound telemarketers, prepaid phone cards or phone services, rebate based businesses, up-sell merchants, bill payment services, betting, manual or automated cash disbursements, prepaid cards, checks, or other financial merchandise or services, sales of money-orders or foreign currency, wire transfer money orders, high-risk products and services, service station merchants,  automated fuel dispensers, adult entertainment oriented products or services, sales of firearms, firearm parts or hardware, and ammunition; or weapons and other devices designed to cause physical injury (24) internet OR telephone order cigarette or tobacco sales, drug paraphernalia,  occult materials, hate or harmful products, escort services, or bankruptcy attorneys or collection agencies engaged in the collection of debt.</p>
                <p>By creating an Account as a Professional, agree that Hair Decoded may send email or other electronic communications on your behalf in connection with the Styling Services offered by you.</p>

                <h2 class="heading01">Payment Processing Services</h2>
                <h2 class="heading01 pad-top-none">Our Role</h2>

                <p>The Services allow Clients to pay and Professionals to accept fees, including Card-based payments initiated with Cards bearing the trademarks of MasterCard International Inc. and Visa Inc. Hair Decoded helps the processing of payments Professionals receive from Clients. This means that we collect, analyze and relay information generated in connection with these payments.</p>
                <h2 class="heading01">Authorization</h2>
                <p>Professionals give us the authority to hold, receive, and disburse funds on your behalf. Your authorization permits us to generate a paper draft or an electronic funds transfer to process each payment transaction that you authorize. Your authorizations will remain in effect until your Account is terminated.</p>
                <h2 class="heading01">Third Party Payment Service Provider</h2>
                <p>Users are expected to provide their credit card or bank account details to the Company and the Payment Service Provider retained by Hair Decoded (from hereon, the "PSP"). As a condition of Hair Decoded enabling payment processing services through the PSP, you agree to provide Hair Decoded with correct information about you and your business, and you authorize Hair Decoded to share it and transaction information related to your use of the PSP services.</p>
                <p>Professionals may be required to register with the PSP, respond to a PSP Account Agreement and the Terms of Service of the PSP and go through a vetting process at the request of the PSP to set up their account with the PSP.</p>
                <h2 class="heading01">Unauthorized Use</h2>
                <p>We may choose not to authorize any transaction that you submit to us if we believe in our sole discretion that the transaction is in violation of this Agreement, or that it exposes Professionals, other Hair Decoded Users, the PSP or Hair Decoded to harm. If we reasonably suspect that your Account has been used for an unauthorized, illegal, or criminal purpose, you give us express authorization to share information about you, your Account, and any of your transactions with law enforcement. You hereby agree to provide us with information and assistance in a timely manner and acknowledge that payment in connection with a suspicious transaction may be delayed until such transaction has been cleared by Hair Decoded.</p>
                <h2 class="heading01">Access to Account Funds</h2>
                <p>As a result to the payout schedule identified below, we will deposit amounts received by us for transactions you submit through the Services (less any applicable Fees) to your verified bank account.</p>
                <p>If the bank account you link to your Account is incorrect and Hair Decoded is not able to debit or credit the bank account, the bank account will be de-linked from your Account. Funds will be deposited only when the transaction is deemed complete. Transactions will be deemed complete when we have received or sent the funds and when we or the financial institutions have accepted the funds.</p>

                <h2 class="heading01">Standard Schedule of Payouts</h2>
                <p>Upon validation of your US bank account, and verifying that you have ten dollars or more in your Account, Hair Decoded will automatically initiate a payout to your bank account at the end of every business day. If the payment is received before 4pm Pacific Time, the payout to your bank account will usually fund the next business day.</p>

                <h2 class="heading01">Availability of Funds</h2>
                <p>In the event that Hair Decoded needs to conduct an investigation or resolve any pending dispute related to your Account, we may restrict access to your funds for the entire time it takes for us to do so. We also may defer payout or restrict access to your funds if requested by law enforcement or governmental entity.</p>
                <h2 class="heading01">Taxes</h2>
                <p>You agree to be responsible for determining any and all taxes assessed, incurred, or required to be collected, paid, or withheld for any reason in connection your use of our services. You also are solely responsible for collecting, withholding, reporting, and remitting correct Taxes to the appropriate tax authority. Hair Decoded specifically disclaims any liability for Taxes.</p>
                <p>In the event that in a given calendar year you receive more than $20,000 in gross amount of payments and more than 200 payments, Hair Decoded will make a report to the IRS, as required by law, your name, address, Tax Identification Number, or EIN, the total dollar amount of the payments you receive in a calendar year.</p>
                <h2 class="heading01">Customer Care</h2>
                <p>Each Professional is solely responsible for all customer service issues relating to such Professional's goods or services. Hair Decoded is solely responsible for customer service issues relating to any Account, payment, Card processing, debiting or crediting.</p>
                <h2 class="heading01">Refunds and Returns</h2>
                <p>If you accept payment through Card transactions with Hair Decoded, you agree to process returns, and provide refunds and adjustments for, your goods or services through your Account in accordance with these Terms of Service and Network Rules. Network Rules require that you will keep a fair return and cancellation policy; disclose your return or cancellation policy to Clients at the time of purchase, not give cash refunds to a Client in connection with a Card sale unless required by law, and not accept cash or any other item of value for preparing a Card sale refund. The amount of the refund must include any associated taxes required to be refunded and cannot exceed the amount shown as the total on the original sales data.</p>
                <h2 class="heading01">Liability for Chargebacks and Fraudulent Actions</h2>
                <p>The amount of a transaction may be reversed to your Account if the transaction is disputed, reversed by the Network, our processor, or a Client or our financial institution, was not authorized or we have any reason to believe that the transaction was not authorized, or is allegedly unlawful, suspicious, or in violation of the terms of these Terms of Service.</p>
                <p>By using the Services, you hereby relieve Hair Decoded from any liability arising from Fraudulent Actions. You will also use best efforts to promptly notify Hair Decoded of any Fraudulent Actions which may affect the Services. Hair Decoded reserves the right, in its sole discretion, to terminate the account of any User that engages in, or enables any other User to engage in fraudulent Actions.</p>
                <h2 class="heading01">Collection Rights for Chargebacks</h2>
                <p>For transactions that result in a Chargeback, we may keep the Chargeback amount in a Reserve. We may debit the amount of any Chargeback and any associated Fees, fines, or penalties listed in the Fee Schedule or assessed by the Association or our processor from your Account, any proceeds due to you, your bank account, or other payment instrument registered with us. If you have pending Chargebacks, we may delay payouts from your Account. </p>
                <h2 class="heading01">Excessive Chargebacks</h2>
                <p>If we believe that you are incurring an excessive amount of Chargebacks, we may create conditions to regulate your Account, by establishing new processing fees, creating a Reserve in an amount reasonably determined by us to cover anticipated Chargebacks and related fees, delaying payouts, and terminating or suspending the Services.</p>
                <h2 class="heading01">Contesting Chargebacks</h2>
                <p>You hereby agree to facilitate when requested, at your expense, an investigation into any of your transactions processed through the Services. To that end, you grant us permission to share information about a Chargeback with the Client, the Client's financial institution, and your financial institution in order to investigate or mediate a Chargeback. We reserve the right to charge a fee for mediating or investigating Chargeback disputes.</p>
                <h2 class="heading01">Set-off Rights</h2>
                <p>You agree to grant us a security interest in, as well as a right of setoff against, and hereby assign, convey, deliver, pledge and transfer to us, as security for repayment of any obligations due under these Terms of Service, all of your right, title, and interest in and to all of your accounts with us. </p>
                <h2 class="heading01">Inactive Accounts</h2>
                <p>If there your Account is inactive for at least two years, consecutively, and you have a balance, we will notify you by sending an email and give you the option of keeping your Account open and maintaining or withdrawing the balance. If you do not respond to our notice within thirty days, we will automatically close your Account and escheat your funds in accordance with applicable law and if permitted to Hair Decoded.</p>
                <h2 class="heading01">Processing Errors</h2>
                <p>Hair Decoded will make an attempt to rectify processing errors that we discover. If the error resulted in your receipt of less than the amount to which you were entitled, Hair Decoded will credit your Account for the difference. If the error results in your receipt of more than the amount to which you were entitled, Hair Decoded will debit the extra funds from your Account. Hair Decoded will only correct transactions that you process incorrectly if and when you notify us of such an error. </p>
                <h2 class="heading01">Professional's Loyalty Programs</h2>
                <p>Professionals may choose to offer loyalty programs to Clients. If a Professional offers such a loyalty program, the Professional is responsible for making sure that its program and any associated rewards are compliant with applicable federal and state laws.</p>
                <h2 class="heading01">Programs</h2>
                <p>We may provide certain programs, promotions, opportunities, sweepstakes and contests to Users. Hair Decoded may at any time in its sole discretion, change, modify, add to, supplement or delete the terms and conditions of any Hair Decoded Program, including without limitation changing the name, fees and eligibility of requirements to participate in such a Program.</p>


                <h2 class="heading01">Limitations and Changes to the Services.</h2>
                <p>Hair Decoded is constantly innovating and finding ways to provide our users with new features and services. Therefore, we may, without prior notice, change the Service, add features, stop providing the Service or features of the Service to you or to users generally, or create usage limits for the Service. We may permanently or temporarily terminate, downgrade, suspend, or prohibit your access to the Service without prior notice and liability for any reason. You acknowledge that the operation of the Services may from time to time encounter technical or other problems and may not necessarily continue uninterrupted or without technical or other errors and Hair Decoded shall not be responsible to you or others for any such interruptions, errors or problems or an outright discontinuance of the Services. Hair Decoded has no obligation to maintain or update the Services or to continue producing or releasing new versions of the Services.</p>
                <h2 class="heading01">HIPAA Notice</h2>
                <p>You agree not to share any protected health information with service providers via the Service. The Services are not intended to be used to transmit protected health information, and it is not intended to be compliant with the Health Insurance Portability and Accountability Act.</p>
                <h2 class="heading01">Proprietary Rights</h2>
                <p>The Services is made up of content and technology of the Company that is protected by copyright, trademark, and other laws. The Company owns intellectual property rights to any protectable part of the Services. You may not copy, modify, or reverse engineer any part of the Services or the Company Property.</p>
                <p>The company needs to use of your publicly posted content in order to operate the Services. Therefore by posting on Hair Decoded, you represent that you have full authorization to do so. You also hereby grant Hair Decoded a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use, distribute, reproduce, modify, adapt, publicly perform, publicly display and make derivative works of such Content in connection with the Services and any services or products affiliated with the Services, regardless of the form of media used or of whether such services or products now exist or are developed in the future. The Company reserves the right to remove or hide any Content from the Services, at its sole discretion.</p>
                <h2 class="heading01">Disclaimers</h2>
                <p>YOU FULLY UNDERSTAND AND AGREE THAT:</p>
                <p>YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. YOU ARE FULLY AND SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER HAIR DECODED USERS AND YOU AGREE THAT IT IS SOLELY YOUR RESPONSIBILITY TO TAKE PRECAUTIONS IN ALL ACTIONS AND INTERACTIONS WITH OTHER PROFESSIONALS AND CLIENTS AND IN THE PROVISION OR RECEIPT OF STYLING SERVICES. </p>
                <p>IT IS POSSIBLE FOR OTHERS TO OBTAIN YOUR PERSONAL INFORMATION DUE TO YOUR USE OF THE SERVICES OR STYLING SERVICES, AND THE RECIPIENT MAY USE SUCH INFORMATION TO HARASS OR CAUSE INJURY TO YOU. WE ARE NOT RESPONSIBLE FOR THE USE OF ANY PERSONAL INFORMATION THAT YOU DISCLOSE ON THE SERVICES OR THROUGH THE SERVICES. YOU UNDERSTAND THAT IN USING THE SERVICES, SENSITIVE INFORMATION WILL TRAVEL THROUGH THIRD-PARTY INFRASTRUCTURE THAT HAIR DECODED DOES NOT CONTROL (SUCH AS THIRD-PARTY SERVERS). HAIR DECODED MAKES NO WARRANTY WITH RESPECT TO THE SECURITY OF SUCH THIRD-PARTY INFRASTRUCTURE.</p>
                <p>THE SERVICE AND ALL CONTENT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, CURRENTNESS, FREEDOM FROM INTERRUPTION, VIRUSES OR OTHER DEFECT, AND NON-INFRINGEMENT.</p>
                <p>HAIR DECODED MAKES NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, THAT YOUR ACCESS TO OR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR FREE, THAT ANY DEFECTS IN THE SERVICES WILL BE CORRECTED, OR THAT THE SERVICES OR ANY SERVER THROUGH WHICH YOU ACCESS THE SERVICES IS FREE OF HARMFUL COMPONENTS.</p>
                <p>HAIR DECODED MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE QUALITY, SUITABILITY, RELIABILITY, TIMING, DURABILITY, LEGALITY, OR ANY OTHER ASPECT OF STYLING SERVICES OFFERED OR PROVIDED BY PROFESSIONALS OR REQUESTED BY CLIENTS.</p>
                <p>ANY MATERIAL OBTAINED THROUGH THE USE OF THE SERVICES IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>
                <p>NO INFORMATION OBTAINED BY YOU FROM HAIR DECODED OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF SERVICE.</p>
                <h2 class="heading01">Limitation of Liability and Release</h2>
                <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HAIR DECODED NOR ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR BODILY INJURY OR EMOTIONAL DISTRESS AND DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM (I) THE USE OR THE INABILITY TO USE THE SERVICES; (II) STYLING SERVICES FACILITATED BY THE SERVICES OR ANY INTERACTIONS BETWEEN USERS, INCLUDING WITHOUT LIMITATION ANY LIABILITIES ARISING IN CONNECTION WITH THE CONDUCT, ACT OR OMISSION OF ANY USER (INCLUDING STALKING, HARASSMENT THAT IS SEXUAL OR OTHERWISE, ACTS OF PHYSICAL VIOLENCE, AND DESTRUCTION OF PERSONAL PROPERTY) OR ANY DISPUTE WITH ANY USER; (III) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; (IV) ANY UNAUTHORIZED ACCESS TO OR ALTERATION OF THE SERVICES OR YOUR DATA OR TRANSMISSIONS; OR (V) ANY OTHER MATTER RELATING TO THE SERVICES.</p>
                <p>SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU.</p>
                <p>HAIR DECODED EXPRESSLY DISCLAIMS ANY LIABILITY THAT MAY ARISE BETWEEN USERS RELATED TO OR ARISING FROM USE OF THE SERVICES. BECAUSE HAIR DECODED IS NOT INVOLVED IN THE ACTUAL INTERACTIONS BETWEEN PROFESSIONALS AND CLIENTS OR IN THE PROVISION OF ANY STYLING SERVICES, YOU HEREBY RELEASE AND FOREVER DISCHARGE HAIR DECODED AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND LICENSORS FROM ANY AND ALL CLAIMS, DEMANDS, DAMAGES (ACTUAL OR CONSEQUENTIAL) OF EVERY KIND AND NATURE, WHETHER KNOWN OR UNKNOWN, CONTINGENT OR LIQUIDATED, ARISING FROM OR RELATED TO ANY DISPUTE OR INTERACTIONS WITH ANY OTHER USER, WHETHER ONLINE OR IN PERSON, WHETHER RELATED TO THE PROVISION OF STYLING SERVICES OR OTHERWISE.</p>
                <h2 class="heading01">Dispute Resolution</h2>
                <h2 class="heading01 pad-top-none">Informal Negotiations</h2>

                <p>
                    To expedite resolution and reduce the cost of any dispute, controversy or claim related to this Agreement ("Dispute"), you and Hair Decoded agree to first attempt to negotiate any Dispute (except those Disputes expressly excluded below) informally for at least thirty (30) days before initiating any arbitration or court proceeding. Such informal negotiations will commence upon written notice. Your address for such notices is your billing address, with an email copy to the email address you have provided to Hair Decoded. <span class="alert-danger">Hair Decoded's address for such notices is Hair Decoded, Inc., 218A Clara Street, San Francisco, CA 94107 Attention: Legal</span>
                </p>

                <h2 class="heading01">Binding Arbitration</h2>
                <p>If you and Hair Decoded are unable to resolve a Dispute through informal negotiations, all claims arising from use of the Services (except those Disputes expressly excluded below) shall be finally and exclusively resolved by binding arbitration. Any election to arbitrate by one party will be final and binding on the other. YOU UNDERSTAND THAT IF EITHER PARTY ELECTS TO ARBITRATE, NEITHER PARTY WILL HAVE THE RIGHT TO SUE IN COURT OR HAVE A JURY TRIAL. The arbitration will be commenced and conducted under the Commercial Arbitration Rules (the "AAA Rules") of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the AAA website <a href="http://www.adr.org" target="_blank">www.adr.org</a>. Your arbitration fees and your share or arbitrator compensation will be governed by the AAA Rules (and, where appropriate, limited by the AAA Consumer Rules). If your claim for damages does not exceed $ 10,000, Hair Decoded will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in the Federal Rule of Civil Procedure 11(b)). The arbitration may be conducted in person, through the submission of documents, by phone or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by a party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except as otherwise provided in this Agreement, you and Hair Decoded may litigate in court to compel arbitration, stay proceeding pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.</p>
                <h2 class="heading01">Exceptions to Alternative Dispute Resolution.</h2>
                <p>Each party retains the right to bring an individual action in small claims court or to seek injunctive or other equitable relief on an individual basis in a federal or state court located within the Central District of California with respect to any dispute related to the actual or threatened infringement, misappropriation, or violation of a party's intellectual property or proprietary rights.</p>
                <h2 class="heading01">Waiver of Right to be a Plaintiff or Class Member in a Supposed Class Action.</h2>
                <p>YOU AND HAIR DECODED AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A CLASS MEMBER OR IN ANY REPRESENTATIVE CAPACITY OR PROCEEDING. Further, no arbitrator shall consolidate any other person's claims with your claims, and may not otherwise preside over any form of a multi-party or class proceeding. If this specific provision is found to be unenforceable in any way, then the entirety of this arbitration section shall be null and void. The arbitrator may not award declaratory or injunctive relief.</p>
                <h2 class="heading01">Location of Arbitration.</h2>
                <p>Arbitration will happen in San Francisco County, California. You and Hair Decoded agree that for any Dispute not subject to arbitration (other than claims proceeding in any small claims court), or where there's no election to arbitrate, the California state and Federal courts located in San Francisco, California have jurisdiction and you and Hair Decoded agree to subject to the personal jurisdiction of such courts.</p>
                <h2 class="heading01">Governing Law.</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.</p>
                <p>You agree with Hair Decoded that, other than as set forth under the subsection entitled "Waiver of Right to be a Plaintiff or Class Member in a Purported Class Action or Representative Proceeding" in Section 15 above, if any portion of Section 15 entitled "Dispute Resolution" is found illegal or unenforceable, that portion will be severed and the remainder of these Terms of Service will remain in effect. Notwithstanding the foregoing, if the subsection entitled "Exceptions to Alternative Dispute Resolution" in Section 15 is found to be illegal or unenforceable, neither you or Hair Decoded will arbitrate any Dispute falling within that portion of that subsection that is found to be illegal or unenforceable and such Dispute will be decided by a court of competent jurisdiction within San Francisco, California, and you and Hair Decoded agree to submit to the personal jurisdiction of that court.</p>
                <h2 class="heading01">Indemnification</h2>
                <p>You will indemnify, hold harmless, and (at Hair Decoded's request) defend Hair Decoded, its affiliates, and its and their representatives, agents, directors, managers, officers, employees, and shareholders (collectively, the "Hair Decoded Parties") from and against all claims resulting from or relating to: (a) your use, non-use or misuse of, or connection to the Site and the Services; (b) Styling Services facilitated by the Services or any interaction between you and another user; (c) your violation or alleged violation of this Agreement; (d) your violation of any rights, including intellectual property rights, of a third party and otherwise as set out herein; or (v) any third-party claims or damages relating to death, personal injury or emotional distress arising from or related to use of the Services. This defense and indemnification obligations will survive the termination of these Terms of Service and your use of the Services.</p>
                <h2 class="heading01">Privacy</h2>
                <p>The data and information we collect via the Services from Users and others is governed by our Privacy Policy which is available at https://hairdecoded.com/privacy/ and is integrated herein (the "Privacy Policy"). You agree that through your use of the Services, you consent to the collection and use of such data and information.</p>
                <p>By using the Services, you may receive information about Clients or other third parties. You agree to take all measures to protect the privacy and legal rights of individuals whose information you collect, and to provide them with a legally sufficient privacy notice or policy. If you are provided with Sensitive or Personal Information, you must disclose that this Information is being collected and clearly explain the reason for its collection and how the Information will be used. If you store Personal or Sensitive Information, you must do so securely, and in accordance with applicable law.</p>
                <h2 class="heading01">Security</h2>
                <p>Technical and organizational measures designed to secure your personal information from accidental loss and from unauthorized access, use, modification, or disclosure have been put in place. We cannot guarantee that unauthorized third parties will never be able to defeat our security measures, or use your personal information for improper purposes. You acknowledge that you provide your information at your own risk.</p>

            </div>
            <div role="tabpanel" class="tab-pane fade" id="clients">
                <p class="pad-top-15"><strong>Updated: 21 November 2018</strong></p>
                <p><strong>Hair Decoded Inc</strong></p>
                <h2 class="heading01">Terms of Service</h2>
                <p>These Terms of Service (the "Terms of Service")  cover the use of the mobile and internet-based services, business tools offered by  Hair Decoded, Inc. (the "Company," "Hair Decoded," "we" or "us") at and through the website HairDecoded.com (the "Website") and through mobile applications (such as services, applications, and the Website are collectively designated as the "Services"). The Company's Privacy Policy located at <a href="https://www.hairdecoded.com/privacy" target="_blank">https://www.hairdecoded.com/privacy</a> and the Hair Decoded Programs located at <a href="https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs" target="_blank">https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs</a>, as well as any community guidelines or dispute resolution processes that the Company may provide or make available, are all considered part of these Terms of Service and are subsumed by reference into these Terms of Service in their entirety.</p>
                <p>Any reference to these Terms of Service shall include and mean a reference to all such incorporated policies, guidelines, programs, schedules, and processes. In the event of a dispute between these Terms of Service and any other terms shown on the Website, the terms of these Terms of Service shall be applicable and govern, and in the event of a conflict between these Terms of Service and the End User License Agreement in mobile applications (the "EULA"), the terms of the EULA shall take precedence.</p>
                <p>IT IS IMPORTANT THAT YOU, PLEASE READ THESE TERMS OF SERVICE PAINSTAKINGLY. THIS  TIS A LEGAL AGREEMENT BETWEEN HAIR DECODED AND YOU WHICH GOVERNS YOUR USE OF THE SERVICES. YOUR USE OF THE SERVICES  AMOUNTS TO YOUR ACCEPTANCE OF AND AGREEMENT TO ALL OF THE TERMS AND CONDITIONS IN THESE TERMS OF SERVICE AND YOUR ATTESTATION THAT YOU ARE AN ADULT AND ARE 18 YEARS OF AGE OR OLDER. IF YOU OBJECT TO ANYTHING IN THESE TERMS OF SERVICE, YOU ARE NOT PERMITTED TO USE THE SERVICES.</p>
                <p>If you are accepting these Terms of Service and using the Services on behalf of a company, organization, government, or other legal entity, you represent and warrant to Hair Decoded that you have been vested with the full power and authority to do so. The Services are mandated and protected by copyright laws and international copyright treaties and conventions, as well as other intellectual property laws and treaties. The unauthorized reproduction, alteration or distribution of the Services, or any portion of them, may result in stringent civil and criminal penalties, and such infractions will be prosecuted to the maximum extent allowable under the law. The Services are licensed, not sold.</p>
                <h2 class="heading01">The Hair Decoded Services</h2>
                <p>Hair Decoded is a platform that links an array of salons, merchants, stylists and professionals (collectively or individually, "Professionals")  dispensing hair, beauty, and other health and wellness services ("Styling Services") with clients seeking such services ("Clients" or "you"). The Professionals and Clients are both users of the Services provided by Hair Decoded and are in the future referred to collectively as "Users."</p>
                <p>Hair Decoded solely operates a platform for Professionals and Clients to connect and functions only as a medium to engender the provision of Styling Services. Hair Decoded does not provide or contract for Styling Services, and Professionals and Clients contract independently for the provision of Styling Services. Each Client bears sole responsibility for selecting the Professional, the Styling Services to be provided and the location at which Styling Services will be performed, whether on the premises of a Professional or at a site designated by the Client. Any decision by a Client to receive Styling Services or by a Professional to provide Styling Services is a decision made in such person's sole discretion/ best judgment and at their own risk. All Users understand and acknowledge that (i) Hair Decoded does not carry out background checks on Clients and (ii) any provision of Services in a private location inherently increases the risks involved for both Clients and Professionals.</p>
                <p>Hair Decoded does not exercise control over the quality, suitability, reliability, timing, durability, legality, failure to provide, or any other aspect whatsoever of any Styling Services provided by Professionals nor of the integrity, responsibility or any of the actions or omissions whatsoever of any Professionals or Clients. Hair Decoded makes no representations or offers no warranties whatsoever concerning Styling Services offered or provided by Professionals or requested by Clients through use of the Services, whether in public, private, or offline interactions, or about the accreditation, registration or licensing of any Professional.</p>
                <p>You must understand that Hair Decoded does not routinely screen its Users, inquire into the background of its Users or attempt to verify the information provided by any User. Hair Decoded does not verify or confirm that any User is who they claim to be or is accurately representing themselves and does not ascertain or establish any representations concerning Styling Services on the Services. Hair Decoded does not assume any responsibility for the accuracy or reliability of this information or any information provided through the Services.</p>
                <p>Notwithstanding the foregoing, Hair Decoded may, but is under no obligation to, verify the background and experience of Professionals via third-party background check services and first party interviews, including but not limited to a verification of identity and a comprehensive criminal background check, and may terminate a Professional based on any information unearthed during such background checks and first party interviews. Whether or not Hair Decoded conducts a background check or first party interview on a Professional, each Client must personally decide whether a Professional is suited to such Client's needs and should exercise caution and common sense to protect their safety and property, just as they would when interacting with anyone you don't know. NEITHER HAIR DECODED NOR ITS AFFILIATES OR LICENSORS IS RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE, OFFLINE OR OTHERWISE, OF ANY USER OF THE SERVICES AND YOU HEREBY COVENANT TO RELEASE THE COMPANY AND ITS AFFILIATES OR LICENSORS FROM ANY LIABILITY to that. HAIR DECODED AND ITS AFFILIATES AND LICENSORS WILL NOT BE LIABLE FOR ANY CLAIM, INJURY OR DAMAGE ARISING IN CONNECTION WITH YOUR USE OF THE SERVICES.</p>
                <p>In connection with certain services, including Styling Services, for which orders/reservations are made available on the Services, some Professionals may require you to input credit card or other payment information, and such Professionals may charge fees for reservations, including canceled and missed appointments. Professionals are only permitted to do so under any policy posted on such Professional's Hair Decoded landing page at the time of your booking. By entering your payment information on request, you authorize Hair Decoded and its payment processors to charge and process the charges assessed in connection with your reservations under the policy described on the Professional's Hair Decoded page at the time of your booking. While Hair Decoded takes what it believes to be reasonable efforts to ensure secure transmission of your information to third parties who assess and process payments, Hair Decoded bears no responsibility for any fees or charges assessed by third parties or any errors in the processing of payments by third parties, including any errors that result from third-party negligence, improper transmission of payment information, your mistaken submission of payment information, or your submission of erroneous payment information among other outcomes.
                    Hair Decoded does not guarantee the availability of Services to the user at every point in time.</p>
                <p>Hair Decoded, may from time to time, either as a Hair Decoded Program (described in the relevant section below) or otherwise, provide certain services to Users for an additional fee that may, among other things, enable Professionals and Clients to work more seamlessly. For a detailed listing of such Hair Decoded Programs in effect as of today, please go over to <a href="https://hairdecodedthelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs" target="_blank">https://hairdecodedthelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs</a></p>

                <h2 class="heading01">Registration of Accounts</h2>
                <p>By creating an account with Hair Decoded (an "Account"), you exercise the right to use the Services provided by Hair Decoded subject to the restrictions outlined in these Terms of Service and any other restrictions stipulated to you by us in written form. Our registration process will ask you for information including your name and other personal information, and in registering for an Account, you agree to provide true, accurate, current and complete information about yourself as prompted by the Services' registration process and as requested from time to time by Hair Decoded (such information, "Registration Data"). You further agree that, in providing such Registration Data, you will not, by the commission, omit or misrepresent any material facts or information and that you will promptly enter corrected or updated Registration information via the Services, or otherwise notify us immediately in writing of any changes or updates to your Registration Data. You further consent and authorize Hair Decoded to verify your Registration Data as required for your use of and access to the Services. Hair Decoded reserves the right to suspend or terminate the Account of any User who provides inaccurate, untrue, or incomplete information, or who fails to adhere to the account registration requirements.</p>
                <h2 class="heading01">Termination of account </h2>
                <h2 class="heading01 pad-top-none">Hair Decoded's Right to terminate</h2>
                <p>Hair Decode possesses the right, in its sole discretion and without recourse to users, to end an Account if it contravenes these Terms of Service or for any reason or no reason at any time. The company may also suspend your access to the Services and your Account ( also covering  the funds in your Account) if you (a) have violated the terms of these Terms of Service, any other agreement you have with Hair Decoded, including without limitation the EULA, or Hair Decoded's policies, (b) present yourself as  an unacceptable credit or fraud risk to us, (c) proffer any false, incomplete, inaccurate, or misleading information or otherwise engage in fraudulent or illegal conduct, or (d) for any other reason in Hair Decoded's determination. You may terminate these Terms of Service and/or the EULA by discontinuing your Account at any time. Upon closure of an Account, any pending transactions will suffer cancellation.</p>
                <h2 class="heading01">Hair Decoded's Payment Processing Procedure</h2>
                <h2 class="heading01 pad-top-none">Hair Decoded's Role</h2>
                <p>The Services provided by Hair Decoded permit  Clients to pay and Professionals to honor payments for Stylist Services, including Card-based payments initiated with Cards bearing the trademarks of MasterCard International Inc. and Visa Inc. (collectively referred  to as the "Networks")through a payment service provider, whose services remains under  retainers by the Company (otherwise called  "PSP"). Be aware that Hair Decoded is not a financial institution and thus, does not offer banking services as outlined by the United States Department of Treasury. Hair Decoded only facilitates the processing of payments Professionals receive from Clients. This entails us collecting, analyzing and relaying information generated in connection with these payments.</p>
                <h2 class="heading01">Authorization</h2>
                <p>By initiating a card-based payment transaction, you authorize Hair Decoded process payments under the Services, using the payment information you have supplied. Users of the Service will be required to provide their credit card or bank account details to Hair Decoded and the PSP.</p>
                <h2 class="heading01">Acceptable Cards for payment</h2>
                <p>Hair Decoded works with any US-issued and most non-US issued credit, debit, prepaid, or gift cards ("Cards") having a Visa, MasterCard, or Discover logo. At the company's sole discretion, accepted cards may be removed or added at any time without prior notice. We will generally only process Cards that receive an authorization from the applicable Network and Card Issuer.</p>
                <h2 class="heading01">Fees chargeable by Hair Decoded</h2>
                <p>Where and if applicable, you agree to pay the appropriate fees listed on our Fee Schedule available at <a href="https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs" target="_blank">https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-HairDecoded-Client-Programs</a> for the use of the Services ("Fees"). Hair Decoded reserves the right to change our Fees immediately upon notice and without recourse to you, the user. You must agree to the change in Fees to continue to use the Services. If you do not consent to the fee change, you will need to close your Account. All balances and all Fees, charges, and payments collected or paid through the Services are settled using the US Dollar.</p>
                <h2 class="heading01">Programs of Hair Decoded.</h2>
                <p>Hair Decoded may from time to time, make available specific programs, promotions, opportunities, sweepstakes and contests to Clients ("Hair Decoded Programs"), descriptions of which can be found at <a href="https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-hairdecoded-Client-Programs" target="_blank">https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260347-hairdecoded-Client-Programs</a>.</p>
                <p>Hair Decoded may at any time in its sole discretion, change, modify, add to, supplement, alter or delete the terms and conditions of any Hair Decoded Program, including without limitation and including changing the name, fees and eligibility requirements to participate in such Hair Decoded Program. The Company will strive to notify users of any material changes by electronic mail, but will not be liable for any failure to do so. In any case, the liability of any of Company's partners about such Hair Decoded Programs shall be limited as described in these Terms of Service, including but not limited to Section 12 of these Terms of Service.</p>
                <p>The Hair Decoded Programs may, among other things, offer certain benefits to Clients for referring Professionals or Clients to the Services. The Hair Decoded Programs may offer certain exclusive services for additional fees to certain classes of users. At present, each User will have the option to join that Hair Decoded Program. Note, however, in the future, the participation in Hair Decoded Programs may become compulsory for individual Users. The Company's general terms and conditions for promotional offers and campaigns (including offers where users must redeem a promotional code as part of the offer) that are not otherwise described or made available on the Website or mobile application will be available <a href="https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260367-General-HairDecoded-Promotional-Terms" target="_blank">https://hairdecodedhelp.zendesk.com/hc/en-us/articles/225260367-General-HairDecoded-Promotional-Terms</a>.</p>
                <p>If any future changes to these Terms of Service are unacceptable to you or cause you to no longer comply with these Terms of Service, you can and must terminate, and immediately stop using, the Services, immediately.</p>
                <h2 class="heading01">Gift Cards</h2>
                <p>At times and under the circumstances in Company's sole behest, Hair Decoded may issue to certain Users gift cards ("Gift Cards") that can be employed to pay for Services, including the Styling Services, and fees or other costs associated with the Services. Gift Cards are not replaceable if lost or stolen and have no expiration date, but in certain states, after a period, we may be required to remit the cash associated with unused Gift Card balances to certain states in consonance to their abandoned property laws. </p>
                <p>Once we have paid such cash to a state if an individual tries to redeem the Gift Card, it may no longer be redeemed, and we may direct them to that state's government instead. Gift Cards are not redeemable by the Hair Decoded for cash except in circumstances as required by applicable law. If a user wishes to redeem his/her Gift Card and such a step is supported under  enabling law, simply send your Gift Card along with a self-addressed envelope to 300  Bennette Boulevard, San Francisco, CA 84109, marked "Attention: Gift Cards." Hair Decoded will ascertain your address, confirm that your Gift Card balance qualifies you for redemption, and send you a check for the exact amount in the envelope provided. If we reach the conclusion that the Gift Card is not required to be redeemed under applicable law, or we can't verify your resident status, we'll return your Gift Card in the envelope provided.</p>
                <p>Hair Decoded will be unable to redeem or return your Gift Card without a self-addressed envelope and bears no responsibility for mail that doesn't arrive at the address provided and cannot offer guarantees on delivery in any way after submittal to the US Postal Service. It is important to note that a Gift Card cannot be combined with any other Gift Cards, gift certificates or other coupons for any given individual transaction on the Website. A Gift Card cannot be employed as a credit or debit card. Hair Decoded reserves the right to limit quantities of Gift Cards purchased by any person or entity and to cancel a Gift Card if it believes that the Gift Card was obtained through dubious or unauthorized means.</p>
                <p>No credit card, credit line, overdraft protection, or deposit account bears any association with your Gift Card. You cannot "reload" (i.e., you cannot add value/balance to your Gift Card at this time). If a Gift Card holder's purchase exceeds the amount of that Gift Card's balance, the Gift Card holder must pay the difference by another means. Unused Gift Card balances are not transferable. Hair Decoded reserves the right to correct the balance of a Gift Card if the Company believes that a billing error has occurred. Hair Decoded absolves itself of all liability for any such billing errors. Gift Cards and their use are subject to these Terms of Service, and the use of a Gift Card constitutes acceptance hereof. Note that unused Gift Card balances cannot be transferred to another user.</p>


                <h2 class="heading01">Use of Services covering Limitations and Changes to the Services of Hair Decoded</h2>
                <p>Note that Hair Decoded may change, modify, suspend, alter or discontinue all or any part of the Services at any time, with or without reason and without recourse to users. You acknowledge that the operation of the Services may from time to time experience technical, functional or other problems and may not necessarily continue uninterrupted or without technical or other errors and Hair Decoded shall not be responsible to users for any such interruptions, disruptions, errors or problems or an outright stoppage of the Services. Hair Decoded is under no obligation to maintain or update the Services or to continue producing or releasing new versions of the Services.</p>
                <p>Hair Decoded will make  every reasonable effort to keep the Services up and running 24 hours a day/7 days a week, except for circumstances such as (i) planned downtime (of which Hair Decoded will endeavor to provide at least 8 hours prior notice); or (ii) any unavailability precipitated by circumstances beyond our control, including but not limited to, acts of God, acts of government, acts of nature such as flood, fire, earthquakes;  civil unrest, acts of terror, strikes or other labor problems or Internet service provider failures or delays.</p>
                <p>As a User of the Services, you consent to follow all applicable rules and laws and take full responsibility for any promotion you offer via the Services. When you publish content or information using the "public" setting feature, it means that everyone and anyone, including people outside of the Hair Decoded community, will have access to that information and Hair Decoded may not have control over what they do with it. We always appreciate your feedback or other suggestions about  Hair Decoded, but you understand that we may use them and you as a result of this, grant us all rights to such suggestions without any obligation to compensate you for them (just as you under no obligation to offer them).</p>
                <p>We do our best to keep Hair Decoded safe and spam free, but no guarantees are given. To help us do so, you consent not to: 1. transmit or otherwise post unauthorized commercial communications (such as spam) on the Services portal. 2. Obtain Users' content or information, or otherwise access the Services, using automated means (such as harvesting bots, robots, spiders, or scrapers) without our permission. 3. Engage in unlawful multi-level marketing, such as a pyramid scheme, on the Services. 4. Upload viruses or other malicious code.5. Ask or request login information or Account IDs or access an account belonging to another individual.6. Engage in bullying, intimidating, or harassing any User. 7. Post content that is hateful, threatening, and pornographic or that contains nudity or graphic or gratuitous/inciting violence. 8. Design, develop, advertise or otherwise market alcohol-related or other mature content. 9. Use Hair Decoded to do anything unlawful, misleading, malicious, or discriminatory. 10. Engage in anything that could disable, overburden, or impair the proper working of StyleSeat or the Services, such as a denial of service attack. 11. Facilitate or encourage any violations of these Terms of Service. 12. To ensure we can provide a service to our Users and customers, we need to make sure our pages are accurate and up-to-date. To help us do so, users agree to. 13. Keep all registration Data and contact information accurate and updated. 14. Keep all Account IDs and Account information confidential and do not share your login information or Account IDs, permit anyone else to access your Account, or do anything else that might threaten the security of your Account.</p>
                <h2 class="heading01">Notice of the HIPAA</h2>
                <p>Users should not disclose any protected health information with service providers via the Services. The Services are not purposed to communicate protected health information, and it is not intended to be compliant with the Federal Health Insurance Portability and Accountability Act (HIPAA). The term "protected health information" connotes any information that relates to the past, present or future bodily or mental health or condition of an individual; the provision of health care to an individual; or the past, present or future financing for the provision of health care services to an individual. If you do disclose any protected health information, note that you perform such action at your own risk.</p>
                <h2 class="heading01">Proprietary Rights</h2>
                <p>Hair Decoded provides content and technology that is protected by copyright, trademark, patent, trade secret and other laws. Hair Decoded exercises exclusive intellectual property rights to any protectable part of the Services, including but not limited to the design, artwork, logos, functionality, and documentation (collectively, the "Company Property"). AS a user, you may not copy, modify, or reverse engineer any part of the Services or the Company Property.</p>
                <p>In order to operate the Services, Hair Decoded needs to make specific use of your publicly posted Content. Therefore, by posting, uploading or submitting to Hair Decoded or making available for inclusion in publicly accessible areas of Hair Decoded, any text, images, photos, graphics, audio or video, including any content protected by intellectual property rights (collectively, "Content"), you aver  that you have full authorization to do so.</p> 
                <p>You also hereby grant Hair Decoded a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use, distribute, reproduce, modify, adapt, publicly perform, publicly show and make related works of such Content in connection with the Services and any services or products affiliated with the Services, irrespective of the form of media used or of whether such services or products now exist or are developed in the future. This license is in operation only for as long as you choose to continue to include such Content on Hair Decoded and will reach expiration at the time such Content is removed from the Services by you or by Hair Decoded; provided that the license will not terminate and will continue notwithstanding any removal of the Content or termination of your use of the Services to the extent that Hair Decoded needs to use such Content in connection with any inquiry/investigation or in obedience with any laws.</p>
                <p>The user covenants not to post any images containing written text or text overlays. Images may not have symbols or text-images anywhere in the photo, including but not limited to shapes, logos, or emoticons, etc. Hair Decoded will enforce its right to remove or hide or change any images without notice or recourse to the user. When you delete Content, the deletion process is similar to emptying the recycle bin on a computer. Note, however, that removed Content may exist in backup copies for a period (but will not be available to others).</p>
                <p>The user acknowledges that all derivative designs and artwork which utilize the Company's logo or other Company Property (collectively, "Derivative Works") are the sole property of Hair Decoded. No other rights are granted to the user concerning the Company Property other than those rights granted explicitly herein, including any Derivative Works. Any Content posted by a User belongs to the person that uploaded such Content. Users can employ any Content posted by them in any way without restriction. Users may only use Content posted by others in the methods described in these Terms of Service.</p>
                <p>The Company reserves the right to remove or hide any Content from the Services, at its sole discretion, without recourse to users. The <strong>Company respects the</strong> intellectual property rights of others. It may, in suitable circumstances and at its discretion, disable and/or terminate the Accounts of Users who the Company, in its determination, believes have repeatedly violated the rights of other users.</p>
                <p>If you, as a user of the services of Hair Decoded, believe that your work has been copied in a way that amounts to copyright infringement, or your intellectual property rights have been otherwise violated, please provide the following information to the Company's copyright agent via email to <a href="mailto:copyright@hairdecoded.com">copyright@hairdecoded.com</a> or by mail to Hair Decoded, Inc., Attn: Copyright Agent, Hair Decoded, Inc., 300 Bennette Boulevard, San Francisco, CA 84109: 1. An electronic or physical signature of the individual authorized to act in the stead of the owner of the copyright or other intellectual property interest; 2. a description of the copyrighted work or other intellectual property that you claim has been infringed; 3.a description of where the material that you claim is infringing is located on the site, including a URL link; 4.your current  address, telephone number, and email address; 5. A pronouncement by you that you have a good faith belief that the disputed copyright use is not authorized or consented to by the copyright owner, its agent, or the law; and 6.a statement by you, made under penalty of perjury in case you lie under oath, that the above information in your notice is entirely accurate and that you are the copyright or intellectual property owner or are authorized to act on the copyright or intellectual property owner's stead.</p>
                <p>Hair Decoded reserves the right to send Clients a newsletter periodically if they opt-in to receiving one. This communication will be highly targeted based on how each Client uses Hair Decoded and will be designed to inform Clients of how to get more value from the Services. As part of the Services, Hair Decoded offers Professionals the choice to send SMS and email messages to their Clients for various reasons such as reminding them of an upcoming appointment. By agreeing to these Terms of Service and using such tools, each Professional posits that it has permission from each Client to send SMS and email notifications and that each Professional takes full responsibility for adhering to each Client's preference concerning such information notices.</p>
                <p>As part of the Services, Hair Decoded may send SMS messages to Users regarding product developments, marketing communications, and other information regarding the Services. Hair Decoded may also send SMS messages to Users regarding upcoming appointments and other reminders using a short code text messaging service. </p>
                <p>The following guidelines apply to the Company's short code text messaging service: 1. When Users select to receive the service, we will send you an SMS message to confirm your signup. 2. Users can cancel the SMS service at any time they desire - just text "STOP" to 789537. After you send the SMS message "STOP" to us, we will send you an SMS message to confirm that you have been taken off the SMS notification service. After this, the user will no longer receive SMS messages from Hair Decoded. 3. If the user wants to opt-in again, he or she just needs to sign up as they did the first time and Hair Decoded will start sending SMS messages to the user again. 4. If at any time you forget what keywords are configured, just text "HELP" to 788699. 5. After you send the SMS message "HELP" to us, we will reply with step-by-step instructions on how to use our service as well as how to unsubscribe. 6. Hair Decoded delivers messages to the following mobile phone carriers: Major Telecom Partners: AT&amp;T, Verizon Wireless, Sprint, T-Mobile, U.S. Cellular, Alltel, Boost Mobile, Nextel, and Virgin Mobile. Minor Telecom Partners: Alaska Communications Systems (ACS), Appalachian Wireless (EKN), Bluegrass Cellular, Cellular One of East Central IL (ECIT), Cellular One of Northeast Pennsylvania, Cincinnati Bell Wireless, Cricket, Coral Wireless (Mobi PCS), COX, Cross, Element Mobile (Flat Wireless), Epic Touch (Elkhart Telephone), GCI, Golden State, Hawkeye (Chat Mobility), Hawkeye (NW Missouri), Illinois Valley Cellular, Inland Cellular, iWireless (Iowa Wireless), Keystone Wireless (Immix Wireless/PC Man), Mosaic (Consolidated or CTC Telecom), Nex-Tech Wireless, NTelos, Panhandle Communications, Pioneer, Plateau (Texas RSA 3 Ltd), Revol, RINA, Simmetry (TMP Corporation), Thumb Cellular, Union Wireless, United Wireless, Viaero Wireless, and West Central (WCC or 5 Star Wireless). As usual, message and data rates may apply for any messages sent to you from us and to us from you. You may receive messages including but not limited to requests for appointments, appointments booked, reminders for appointments, tips, and payment receipts.</p>
                <p>If you have any questions about your data/stew plan, it is best to contact your wireless provider. For all questions about the services provided by this shortcode, you can send an email to <a href="mailto:support@hairdecoded.com">support@hairdecoded.com</a>. If you have any further questions about privacy issues, please read our privacy policy available at <a href="https://hairdecoded.com/privacy/" target="_blank">https://hairdecoded.com/privacy/</a></p>

                <h2 class="heading01">Disclaimers</h2>
                <p>YOU, THE USER, EXPRESSLY UNDERSTAND AND AGREE THAT: YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. YOU ARE FULLY AND SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS, AND YOU AGREE THAT IT IS SOLELY YOUR RESPONSIBILITY TO TAKE REASONABLE AND PRACTICAL PRECAUTIONS IN ALL ACTIONS AND INTERACTIONS WITH OTHER PROFESSIONALS AND CLIENTS AND IN THE PROVISION OR RECEIPT OF STYLING SERVICES. HAIR DECODED IS NOT RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE SERVICES. HAIR DECODED IS NOT OBLIGATED TO, AND DOES NOT ROUTINELY, SCREEN ITS USERS, INQUIRE INTO THE BACKGROUND OF ITS USERS OR ATTEMPT THE VERIFICATION OF ANY INFORMATION PROVIDED BY ANY USER. WE RESERVE THE RIGHT, BUT ARE NOT OBLIGATED, TO MONITOR DISPUTES BETWEEN YOU AND OTHER USERS.</p>
                <p>PLEASE, IT IS IMPORTANT TO SELECT CAREFULLY THE TYPE OF INFORMATION THAT YOU POST ON THE SERVICES OR THROUGH THE SERVICES OR RELEASE TO OTHERS. WE DISCLAIM ALL LIABILITY, REGARDLESS OF THE FORM OF ACTION, FOR THE ACTS OR OMISSIONS OF OTHER PARTICIPANTS OR USERS. OTHERS can OBTAIN PERSONAL INFORMATION ABOUT YOU ARISING FROM YOUR USE OF THE SERVICES OR STYLING SERVICES, AND THAT THE RECEIVER MAY USE SUCH INFORMATION TO HARASS OR INJURE YOU. HAIR DECODED IS NOT RESPONSIBLE FOR THE USE OF ANY PERSONAL INFORMATION THAT YOU DISCLOSE ON THE SERVICES OR THROUGH THE SERVICES. YOU UNDERSTAND THAT IN USING THE SERVICES, SENSITIVE INFORMATION/DATA WILL PASS THROUGH THIRD-PARTY INFRASTRUCTURE THAT IS NOT UNDER HAIR DECODED'S CONTROL (SUCH AS THIRD-PARTY SERVERS). HAIR DECODED MAKES NO WARRANTY about THE SECURITY OF SUCH THIRD-PARTY INFRASTRUCTURE. THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. HAIR DECODED AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, AND LICENSORS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS/APPROPRIATENESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. HAIR DECODED MAKES NO GUARANTY THAT (I) THE SERVICES WILL MEET YOUR MINIMUM OR NOT REQUIREMENTS OR EXPECTATIONS, (II) THAT YOUR ACCESS TO OR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, (III) THAT ANY DEFECTS IN THE SERVICES WILL BE CORRECTED, OR (IV) THAT THE SERVICES OR ANY SERVER THROUGH WHICH YOU ACCESS THE SERVICES IS FREE OF VIRUSES OR OTHER HARMFUL ONLINE COMPONENTS. </p>
                <p>HAIR DECODED MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE QUALITY, SUITABILITY, RELIABILITY, TIMING, DURABILITY, LEGALITY, OR ANY OTHER ASPECT OF STYLING SERVICES OFFERED OR PROVIDED BY PROFESSIONALS OR REQUESTED BY CLIENTS THROUGH USE OF THE SERVICES WHETHER IN PUBLIC, PRIVATE, OR OFFLINE INTERACTIONS OR ABOUT THE ACCREDITATION, REGISTRATION OR LICENSE OF ANY PROFESSIONAL. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS ACCESSED AT YOUR SOLE DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE METED TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM HAIR DECODED OR THROUGH OR FROM THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF SERVICE.</p>
                <h2 class="heading01">Limitation of Liability and Release</h2>
                <p>TO THE FULLEST EXTENT ALLOWED BY LAW, UNDER NO CIRCUMSTANCES SHALL HAIR DECODED OR ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS BE HELD RESPONSIBLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR BODILY INJURY OR EMOTIONAL DISTRESS AND DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), ARISING FROM: (I) THE USE OR THE INABILITY TO USE THE SERVICES; (II) STYLING SERVICES FACILITATED BY THE SERVICES OR ANY INTERACTIONS BETWEEN USERS, INCLUDING WITHOUT LIMITATION ANY LIABILITIES ARISING IN CONNECTION WITH THE CONDUCT, ACT OR OMISSION OF ANY USER (INCLUDING WITHOUT LIMITATION STALKING, HARASSMENT THAT IS SEXUAL OR OTHERWISE, ACTS OF PHYSICAL VIOLENCE, AND THE WILLFUL OR ACCIDENTAL DESTRUCTION OF PERSONAL PROPERTY) OR ANY DISPUTE WITH ANY USER; (III) STATEMENTS OR CONDUCT ATTRIBUTABLE TO ANY  THIRD PARTY ON THE SERVICE; (IV) ANY UNAUTHORIZED ACCESS TO OR ALTERATION OF THE SERVICES OR YOUR DATA OR TRANSMISSIONS; OR (V) ANY OTHER MATTER INCIDENT TO THE SERVICES.</p>
                <p>Note, however, that some jurisdictions do not permit the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations may not apply to you.</p>
                <p>HAIR DECODED EXPRESSLY AND EXPLICITLY DISCLAIMS/DISOWNS ANY LIABILITY THAT MAY ARISE BETWEEN USERS RELATED TO OR ARISING FROM USE OF HAIR DECODED SERVICES. BECAUSE HAIR DECODED DOES NOT PARTICIPATE IN THE ACTUAL INTERACTIONS BETWEEN PROFESSIONALS AND CLIENTS OR IN THE PROVISION OF ANY STYLING SERVICES, YOU HEREBY COVENANT TO RELEASE AND FOREVER DISCHARGE/ABSOLVE HAIR DECODED  AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND LICENSORS FROM ANY AND ALL CLAIMS, DEMANDS, DAMAGES (ACTUAL OR CONSEQUENTIAL) OF EVERY KIND AND NATURE, WHETHER KNOWN OR UNKNOWN, CONTINGENT OR LIQUIDATED, ARISING FROM OR RELATED TO ANY DISPUTE OR INTERACTIONS WITH ANY OTHER USER, WHETHER ONLINE OR IN PERSON, WHETHER RELATED TO THE PROVISION OF STYLING SERVICES OR OTHERWISE</p>
                <h2 class="heading01">Indemnification</h2>
                <p>The user  agrees to defend, indemnify and hold blameless the Company and its affiliates, officers, directors, employees, agents, partners and licensors from and against any and all claims, damages, obligations, losses, liabilities, costs, debt and expenses (including but not limited to attorney's fees) arising from or relating to: (i) your use of and access to the Services; (ii) Hair, Styling and other affiliated  Services facilitated by the Services or any interaction between you and another user; (iii) your violation of any term of these Terms of Service; (iv) your violation of any rights of a third party, including without limitation any copyright, intellectual property, or privacy right; or (v) any third-party claims or damages  pertaining to death, personal injury or emotional distress arising from or related to use of the Services. This defense, absolving and indemnification obligations will outlive the termination of these Terms of Service and your use of the Services by Hair Decoded.</p>
                <h2 class="heading01">Dispute Resolution</h2>
                <h2 class="heading01 pad-top-none">Negotiations outside formal circles</h2>
                <p>For a quick and less expensive resolution of any dispute, controversy or claim arising from or relating to these Terms of Service, you and Hair Decoded covenant to first attempt to negotiate any Dispute (except those Disputes explicitly  excluded below) outside formal circles for a minimum of  thirty (30) days before initiating any lawsuit or court proceeding. Such informal negotiations will commence upon written notice, served to both parties. Your address for such notices shall be your billing address, with a copy to the email address you have provided to Hair Decoded. Hair Decoded's address for such legal notifications  is Hair Decoded, Inc., 300  Bennette Boulevard, San Francisco, CA 84109, marked as 'Attention: Legal."</p>
                <h2 class="heading01">Binding Arbitration</h2>
                <p>If you and Hair Decoded are unable to resolve a dispute through informal negotiations, all claims arising from the use of these Services (except those Disputes expressly excluded below) shall be wholly and exclusively resolved by binding arbitration. Any election to arbitrate by one party will be final and binding on the other. NOTE THAT IF EITHER PARTY CHOOSES THE PATH OF ARBITRATION, BOTH PARTIES FORFEIT THE RIGHT TO SUE IN COURT OR REQUEST A JURY TRIAL.</p>
                <p>The arbitration will begin and be conducted under the Commercial Arbitration Rules (the "AAA Rules") of the American Arbitration Association ("AAA") and, where appropriate, the AAA's Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available for further scrutiny at the AAA website <a href="http://www.adr.org" target="_blank">www.adr.org</a>.</p>
                <p>The user's arbitration fees and your share of arbitrator compensation will be governed by the AAA Rules (and, where appropriate, limited by the AAA Consumer Rules). If  user's claim for damages does not exceed USD 10,000, Hair Decoded will pay all such amounts unless the arbitrator finds that either the substance of your application or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in the Federal Rule of Civil Procedure 11(b)).</p>
                <p>The arbitration may be performed in person, through the submission of documents, by telephone or online. The arbitrator will give a decision in writing but is not bound to provide a statement of reasons unless requested by a party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except as otherwise provided in these Terms of Service, you and Hair Decoded may litigate in court to force arbitration,  obtain a stay of proceeding pending arbitration or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.</p>
                <h2 class="heading01">Exceptions to Alternative Dispute Resolution.</h2>
                <p>Note that claims where a valid, non-preempted law prohibits mandatory arbitration, including claims under the Private Attorney General Act of 2004, California Labor Code 2698 et seq. ("PAGA") to the extent waiver of such application is adjudged unenforceable by a court of competent jurisdiction, are not covered by this arbitration provision. Nothing in this arbitration provision will block either party from bringing an individual action in small claims court or to seek injunctive or other obtainable relief on an individual basis in a federal or state court in San Francisco County, California, with respect to any dispute related to the material or threatened infringement, misappropriation or gross violation of a party's intellectual property or proprietary rights.</p>

                <h2 class="heading01">Forfeiture of Right to act as Plaintiff or Class Member in a Purported Class Action Suit or Representative Proceeding.</h2>
                <p>You and Hair Decoded agree that any arbitration will be limited to the Dispute between Hair Decoded and you individually. YOU ACKNOWLEDGE, UNDERSTAND AND AGREE THAT YOU AND HAIR DECODED  ARE EACH FORFEITING THE RIGHT TO ACT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING. Further, unless both you and Hair Decoded otherwise agree, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding.</p>
                <h2 class="heading01">Location of Arbitration</h2>
                <p>Arbitration will take place in San Francisco County, California. You and Hair Decoded agree that for any Dispute not subject to arbitration (other than claims proceeding in any competent small claims court), or where no election to arbitrate has been made, the California state and Federal courts located in San Francisco, California have exclusive jurisdiction and you and Hair Decoded covenant to submit to the personal jurisdiction of such courts.</p>
                <h2 class="heading01">Applicable Law</h2>
                <p>You and Hair Decoded agree and enter into a covenant that other-other than as stated under the subsection entitled "Waiver of Right to be a Plaintiff or Class Member in a Purported Class Action or Representative Proceeding" in Section 15 above, if any portion of Section 15 entitled "Dispute Resolution" is found illegal or unenforceable, that portion will be severed, and the remainder of these Terms of Service will be given full force and effect, to the full extent of the law. </p>
                <p>However, in addition to the foregoing, if the subsection entitled "Exceptions to Alternative Dispute Resolution" in Section 15 is found to be illegal or unenforceable, neither you or Hair Decoded  will choose  to arbitrate a court of competent jurisdiction will decide any Dispute falling within that purview of that subsection that is found to be illegal or unenforceable and such Dispute within the state of authority in the USA, and you and Hair Decoded  agree to submit to the personal judgment of that court. Except as expressly stated otherwise, these Terms of Service are governed by and will be interpreted under, the laws of the State of California, without regard to choice of law principles. </p>
                <p>Notwithstanding the provision in the preceding paragraph with respect to applicable substantive law, the enforceability of Section 15 entitled "Dispute Resolution" shall fall under the Federal Arbitration Act (see 9 U.S.C., Secs. 1-16).</p>
                <h2 class="heading01">Privacy</h2>
                <p>Our collection of data and information via the Services from Users and others is subject to our Privacy Policy which is available at <a href="https://hairdecoded.com/privacy/">https://hairdecoded.com/privacy/</a> and is incorporated herein (as the "Privacy Policy"). Note that through your use of the Services that you unequivocally consent to the collection and use (as stated in the Privacy Policy) of such data and information.</p>
                <h2 class="heading01">Security and Related Matters</h2>
                <p>Hair Decodes instituted elaborate organizational and technical steps/ measures to ensure that users' personal information and data are secure from accidental loss and unauthorized use, theft or alterations. Note, however, that Hair Decoded cannot absolutely guarantee that 
                    These security measures may not prevent third parties from breaching these protocols or putting your personal information to wrong use. It is important to state that users provide their information at their own risk.</p>                    
            </div>
        </div>

    </div>
</section>